= NimでJavaScriptとして出力しHTMLから利用する
// 記事のタグ
// 独自記法のためコメントで表現
// :tag: [nim, javascript]

NimのコードをJavaScriptバックエンドとしてコンパイルして
それをHTMLから利用する方法について記載。

== そもそもJavaScriptバックエンドとは

Nimで書いたコードをコンパイルするとき、何言語にコンパイルするのかを指定する。
`nim c` だとC言語にトランスコンパイルし、 `nim cpp` C＋＋にトランスコンパイル
する。同じ要領で `nim js` とするとJavaScriptにコンパイルする。
JavaScriptバックエンドとは `nim js` でコンパイルすることをここでは指す。

== JSコンパイルする方法

コンパイルするのは簡単で、あるプラグマを追加するだけである。
Nimで別モジュールからプロシージャをインポートするときは `*` という指定が必要だっ
たがJSコンパイルのときは不要。代わりにexportcプラグマが必要になる。

以下にJSからアクセス可能なNimソースを用意した。

[source,nim]
----
include::./js/exportc.nim[]
----

何の変哲もない `add` プロシージャであるが、 `cint` と `{.exportc.}` は見慣れないかも
しれない。

`cint` はNim以外の言語環境とのデータやり取りの際に使用する型である。C言語とやり
取りするときにも c で始まる型でやり取りをする。JSのときも同様である。

`{.exportc.}` はNim以外の環境に公開する際に指定するプラグマである。この指定がな
いとJSからはプロシージャを使用できない。

これらの指定をした上で、以下のコマンドでNimコードをJSにコンパイルする。
コンパイル対象のソースは `js/exportc.nim` であるものとする。

[source,bash]
nim js js/exportc.nim

これでjsディレクトリ配下にnimcacheというディレクトリが生成され、その配下に
exportc.jsというファイルが生成される。
出力先とファイル名を指定したい場合はオプションを指定する。

[source,bash]
nim js -o:static/js/exportc.js js/exportc.nim
# ディレクトリが存在しなくても自動で作成してくれる

== HTML側からコンパイルしたJSにアクセスする方法

HTML側から普通にJavascriptの関数のように関数を呼べば良い。
関数を呼ぶ場合は、当然だがscriptタグでJSを読み込んでおく必要がある。

[source,html]
----
<script src="static/js/exportc.js"></script>

<script>
window.onload = function() {
  console.log(add(1, 2)); // -> 3
}
</script>
----

== JSバックエンドでコンパイルする際に起きる問題

=== ライブラリをJSから利用したいが型が違うケース

https://github.com/jiro4989/gameoflife[ライフゲームのライブラリ]をNimで書いたり
したときに直面したが、ライブラリを書いて、JSから利用したいけれど型が違うのをどう
したらよいか。たとえば以下のようなケース。

[source,nim]
proc add*(a, b: int): int =
  return a + b

このようにライブラリ内では普通のNimの型で書いている場合。
JSから利用しようとしても肩が違うとやりとりできない。しかしJS側にわざわざ合わせた
型にもしたくない(cで始まる型(cintとかcstringとか)は普通にNimコード側から扱おうと
するといちいち型を変換しないといけなくて面倒)。

そういうときはライブラリとは完全に別ファイルに分けてしまって、モジュールをimport
してプロシージャ呼び出しをラッピングシてしまえば良い。
例えば以下のようにする。

lib.nim

[source,nim]
proc add*(a, b: int): int =
  return a + b

libjs.nim

[source,nim]
----
import lib

proc add(a, b: cint): cint {.exportc.} =
  return lib.add(a.int, b.int)
----

こんな感じで、JSとのインタフェースになる箇所はcintなどの型で定義しておき、
やり取りする際は型を変換して渡すようにする。
前述の２つのソースを同じ階層に配置したうえで、以下のようにコンパイルする。

[source,bash]
nim js -o:js/libjs.js js/libjs.nim

これでNim/のソースと同階層にJSファイルがコンパイルされて出力された。
コンパイルしたNimソースがモジュールに依存していても依存先モジュールも合わせてコ
ンパイルしてJSソースに含めてくれるのでそのあたりは気にしなくて良い。

=== JSバックエンドからは利用できないモジュールやプロシージャが存在するケース

Nimのドキュメントには書かれていたりいなかったりするのだが、JSバックエンドからは
利用できないプロシージャがあったりする。ソースコードを読むと分かるが、
`when not defined(js):` というフロックで表現されている箇所はJSからは利用できない
機能になる。利用とするとプロシージャ未定義でコンパイルに失敗する。

できないものは特にos、loggingといったファイルIO周り、posixモジュール、streamsモジュ
ールなど、他にも探しだしたらきりがない。
ファイルIO周りがJSバックエンドで使用できないのはJavaScript自体のセキュリティ上の
制約の都合上なので仕方ない。

逆にstrutilsやsequtilsといったものは普通にJSバックエンドでも利用できる。

利用できないモジュールを使用していたらどうなるか、以下のコードで検証した。

[source,nim]
----
include::./js/ostest.nim[]
----

このコードをコンパイルしてみる。

[source,bash]
nim js -o:js/ostest.js js/ostest.nim

と、以下のようなエラーが発生してコンパイルが失敗する。

[quote]
Error: OS module not ported to your operating system!

見ての通りosモジュールはimportだけでもNGのようだ。
これもosモジュールのソースを読めば理由は分かる。
`when` ブロックでバックエンドが対象外のときはエラーで落ちるように指定が入ってい
る。

ライブラリをimportしたいのに特定のモジュールをimportしていたり特定のプロシージャ
を使おうとしてコンパイルができない、ということはJSバックエンドだとよくある。その
ようなときは、JSバックエンド用に作成したソースでも `when` を使えばよい。

前述のosモジュールをimportしていたソースコードを以下のように修正することでJSバッ
クエンドでコンパイルできるようになる。

[source,nim]
----
include::./js/ostest2.nim[]
----

NimはPython風とよく聞くけれど、オフサイドルール（インデントでブロックを表現する
）のを採用しているだけで、Pythonの皮をかぶったC言語というのは言い得て妙。ところ
どころにC言語の `#ifdef` 地獄の片鱗が見えて恐ろしい。