= 第41回 シェル芸勉強会振り返り
include::../../../metadata.txt[]
// 記事のタグ
// 独自記法のためコメントで表現
// :tag: [bash, シェル芸, 勉強会]

第41回シェル芸勉強会に参加した。初参加です。

== まえがき

2019/4/27 (土)に「jus共催 第41回{ウン,ガク,}{チ,ト,}{,ン}{,コイン}{ブ,}{ラブラ,
ハ,}{,イブ}{無,有}罪シェル芸勉強会」に参加してきたのでその振り返り。
この名称自体もシェル芸で[ブレース展開]という記法。これをechoしてみると以下のよう
になる(※長すぎて[Scrapbox]が固まってしまったので一部抜粋)

[source,bash]
echo jus共催 第41回{ウン,ガク,}{チ,ト,}{,ン}{,コイン}{ブ,}{ラブラ,ハ,}{,イブ}{無,有}罪シェル芸勉強会"\n" | wc -l

[quote]
865

[source,bash]
echo jus共催 第41回{ウン,ガク,}{チ,ト,}{,ン}{,コイン}{ブ,}{ラブラ,ハ,}{,イブ}{無,有}罪シェル芸勉強会"\n" | head

[quote]
jus共催 第41回ウンチブラブラ無罪シェル芸勉強会 +
 第41回ウンチブラブラ有罪シェル芸勉強会 +
 第41回ウンチブラブライブ無罪シェル芸勉強会 +
 第41回ウンチブラブライブ有罪シェル芸勉強会 +
 第41回ウンチブハ無罪シェル芸勉強会 +
 第41回ウンチブハ有罪シェル芸勉強会 +
 第41回ウンチブハイブ無罪シェル芸勉強会 +
 第41回ウンチブハイブ有罪シェル芸勉強会 +
 第41回ウンチブ無罪シェル芸勉強会 +
 第41回ウンチブ有罪シェル芸勉強会

シェル芸勉強会の様子は https://togetter.com/li/1342525[Togetter]にまとまっている。

== 午前の部

* 文字コードの話
* 文字列の結合、絵文字の結合、絵文字の色の変更ができる
* UnicodeData.txtというファイルにユニコード文字のすべてが載っている

== 午後の部

8問のシェルの問題を片っ端からとくというもの。
問題に必要なファイルは https://github.com/ryuichiueda/ShellGeiData[こちら]にある。
シェル芸のコマンドを実際に実行するなら事前に以下のコマンドを実行して準備を整えておく。

[source,bash]
git clone https://github.com/ryuichiueda/ShellGeiData
cd ShellGeiData/vol.41

問題の一覧は https://b.ueda.tech/?post=20190427_shellgei_41_q[こちら]。
以降は問題と自分の回答。

=== Q1

Q.次のファイルについて、2列目をキーにしてエクセルの横列の記号（A, B, ..., Z,
AA, AB, ...のやつ）順に並べ替えてください。

  $ cat excel
  114514 B
  1192296 AA
  593195 CEZ
  4120 TZ
  999 QQQ

=== Q2

Q.次のファイルのレコードを干支順にソートしてください。

  $ cat eto_yomi
  申 さる
  子 ね
  寅 とら
  卯 う
  巳 み
  辰 たつ
  丑 うし
  酉 とり
  戌 いぬ
  亥 い
  午 うま
  未 ひつじ

ただし、次のファイルを補助に使って良いこととします。

  $ cat eto
  子丑寅卯辰巳午未申酉戌亥

=== Q3

Q.次のファイルのレコードを数字（第一フィールドの計算結果）が小さい順に並べてく
ださい。

  $ cat kim_calc
  1+2+4 金正日
  4*3 金正男
  3-1-5 金日成
  495/3 金正恩
  0x1F 金正哲

=== Q4

Q.次のファイルはシフトJISのテキストですが、これを1) 辞書順、2) 数字の小さい順
、にソートしてください。出力もシフトJISとします。

  $ cat sjis | nkf -g
  Shift_JIS
  $ cat sjis | nkf -wLux
  １２３ ずんごるももう
  ３１ こきたてひーひー
  ９ ほじぱんふんじこみ
  ２２４２ たまもとやろう

=== Q5

Q.サイズの小さい順にソートしてください。

  $ cat size 
  2GB
  1.2GB
  40000MB
  1000000000kB
  0.4GB
  410MB

=== Q6

Q.sleepと内部コマンドだけを使って次の数を小さい順にソートしてください。

  $ cat nums
  5.4
  0.34
  2.3
  0.9
  6

=== Q7

Q.次のローマ数字をソートしてください。

  $ cat roman
  IV
  XI
  LXXXIX
  IX
  XLIII
  XX
  VIII

=== Q8

Q.次のファイルを辞書順にソートしてください。ただし、濁点がついているものが先に
来るようにしてください。できる人はワンライナー中で「かきくけこがぎぐげご」の文
字を使わないでください。

  $ cat gagigugego 
  かき氷
  ぎ・おなら吸い込み隊
  きつねうどん
  ぐりこもりなが事件
  きききりん
  がきの使い
  くその役にも立たない
  げんしりょく発電
  ごりらいも
  こじんてきにはクソ
  例
  がきの使い
  かき氷
  ぎ・おなら吸い込み隊
  きききりん
  きつねうどん
  ぐりこもりなが事件
  くその役にも立たない
  げんしりょく発電
  ごりらいも
  こじんてきにはクソ

== LT会

* テキストからドット画像を出力するコマンド
* AlaSQL
* cam
